### PR TITLE
Added Travel planner(route breaking) feature

### PR DESCRIPTION
**Pull request by sphinxominator**

### CODE REVIEW

**Comment by emiltin** [comment]
we need a solution that does block the web app if the rejseplanen api is slow

**Comment by sphinxominator** [comment]
I've switched the server with Puma in another branch. It allows us to maintain concurrent connections and doesn't block the server if rejseplanen is too slow. But I need to check how much it can handle and if there's any other repercussions.

**Comment by emiltin** [comment]
that will not solve the problem that process is blocked. it's simply not a good idea to have long running things going on in the front end app. see eg https://www.twilio.com/blog/2015/10/delay-api-calls-to-twilio-with-rails-active-job-and-sidekiq.html

"Performing long running, blocking tasks during the course of a request is a top way to slow down responses for any web application. I’m talking things like sending emails, generating PDF or CSV files or making HTTP requests to 3rd party APIs."

such things such be deferred to a background process. returning data from a background job is not easy, which is why is question the decision to funnel calls to rejseplanen through the web app.

**Comment by emiltin** [comment]
also "puma is designed to be used on a Ruby implementation which provides true parallelism, such as Rubinius and JRuby"

**Comment by sphinxominator** [comment]
I agree that it's not ideal right now. I'll discuss solutions with the team tommorow.

**Pull request merged**
